### ISSUE TITLE
Boot9Strap 1.2 is a thing now

### ISSUE THREAD

**Issue by coztellation** [xerpi/firm_linux_loader#1]
And it breaks all previous payloads, including this one.
Pls fix, I love showing people "Hey, I have linux on my 3ds" :smiley:

**Comment by xerpi** [comment]
Haha sure, fix incoming!

**Comment by xerpi** [comment]
Fixed with d7655bd37cfbcc5588322f44e39a83d143e469de!

EDIT: New release also: https://github.com/xerpi/firm_linux_loader/releases/

**Comment by coztellation** [comment]
\o/
Thanks! :smile:
